from tkinter import *
from PIL import Image, ImageTk
import threading
from time import sleep
from gpiozero import LED  # allows use of gpio ports


# 1st Octave
c3 = LED(0)
# cs3 = LED(19)
d3 = LED(1)
# eb3 = LED(20)
e3 = LED(2)
f3 = LED(3)
fs3 = LED(4)
g3 = LED(5)
ab3 = LED(6)
a3 = LED(7)
bb3 = LED(8)
b3 = LED(9)
# 2nd Octave
c4 = LED(10)
cs4 = LED(11)
d4 = LED(12)
eb4 = LED(13)
e4 = LED(14)
f4 = LED(15)
fs4 = LED(16)
g4 = LED(17)
ab4 = LED(18)
a4 = LED(19)
bb4 = LED(20)
b4 = LED(21)
# 3rd Octave
c5 = LED(22)
cs5 = LED(23)
d5 = LED(24)
eb5 = LED(25)
e5 = LED(26)
f5 = LED(27)


mainwindow = Tk()

mainwindow.geometry('1500x1500')
mainwindow.title("GUI")
mainwindow.configure(background='black')
image = Image.open("C:/Users/rogel/Desktop/CHAD_LOGO.PNG")
photo = ImageTk.PhotoImage(image)
lab = Label(image=photo)
lab.place()
lab.pack()

song1 = True
song2 = True
song3 = True
song4 = True
stop = False
play = False
pause = False



def switchon():
    global stop
    stop = False
    print("Playing Song")
    FunctionA()


def switchon2():
    global stop
    stop = False
    print("Playing Song")
    FunctionB()


def switchon3():
    global stop
    stop = False
    print("Playing Song")
    functionC()


def switchon4():
    global stop
    stop = False
    print("Playing Song")
    functionD()


def stop1():
    global stop
    stop = True
    print("Ending Song")






def FunctionA(): # Song of Storms
    def run():
        while stop == False:


            i = 0
            while i < 2:  # intro
                # 1 & 3
                if stop == True:
                    return
                d3.on()
                sleep(.9)
                d3.off()
                e3.on()
                sleep(.9)
                e3.off()
                if stop == True:
                    return
                # 2 & 4
                f3.on()
                sleep(.9)
                f3.off()
                e3.on()
                sleep(.9)
                e3.off()
                i += 1


            i = 0
            if stop == True:
                return

            while i < 2:
                if stop == True:
                    break
                # 5 & 7
                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.9)
                e3.off()
                if stop == True:
                    return

                # 6 & 8

                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c4.on()
                sleep(.15)
                f4.off()
                a4.off()
                c4.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.9)
                e3.off()
                i += 1
            if stop == True:
                return


            i = 0
            while i < 2:
                # 9 & 11
                if stop == True:
                    return

                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.3)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e3.off()
                if stop == True:
                    break
                # 10 & 12
                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.3)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e3.off()
                i += 1
                if stop == True:
                    return

            i = 0
            while i < 2:
                # 13 & 15
                if stop == True:
                    return

                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                if stop == True:
                    return

                # 14 & 16
                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                i += 1
                if stop == True:
                    return


            i = 0
            while i < 3:  # main melody
                # 17
                if stop == True:
                    return

                d3.on()
                d4.on()
                sleep(.15)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                d5.on()
                sleep(.6)
                d5.off()
                d3.off()
                e3.on()
                d4.on()
                sleep(.15)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                d5.on()
                sleep(.6)
                e3.off()
                d5.off()
                if stop == True:
                    return

                # 18

                f3.on()
                e5.on()
                sleep(.45)
                e5.off()
                f5.on()
                sleep(.15)
                f5.off()
                e5.on()
                sleep(.15)
                e5.off()
                f5.on()
                sleep(.15)
                f5.off()
                f3.off()
                e3.on()
                e5.on()
                sleep(.15)
                e5.off()
                c5.on()
                sleep(.15)
                c5.off()
                a4.on()
                sleep(.6)
                e3.off()
                a4.off()
                if stop == True:
                    return
                # 19
                bb3.on()
                a4.on()
                sleep(.3)
                a4.off()
                d4.on()
                sleep(.3)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                g4.on()
                sleep(.15)
                bb3.off()
                g4.off()
                f3.on()
                a4.on()
                sleep(.45)
                a4.off()
                sleep(.45)
                f3.off()
                if stop == True:
                    return

                # 20
                bb3.on()
                a4.on()
                sleep(.3)
                a4.off()
                d4.on()
                sleep(.3)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                g4.on()
                sleep(.15)
                bb3.off()
                g4.off()
                a3.on()
                e4.on()
                sleep(.9)
                a3.off()
                e4.off()
                if stop == True:
                    return

                # 21
                d3.on()
                d4.on()
                sleep(.15)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                d5.on()
                sleep(.6)
                d5.off()
                d3.off()
                e3.on()
                d4.on()
                sleep(.15)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                d5.on()
                sleep(.6)
                e3.off()
                d5.off()
                if stop == True:
                    return

                # 22

                f3.on()
                e5.on()
                sleep(.45)
                e5.off()
                f5.on()
                sleep(.15)
                f5.off()
                e5.on()
                sleep(.15)
                e5.off()
                f5.on()
                sleep(.15)
                f5.off()
                f3.off()
                e3.on()
                e5.on()
                sleep(.15)
                e5.off()
                c5.on()
                sleep(.15)
                c5.off()
                a4.on()
                sleep(.6)
                e3.off()
                a4.off()
                if stop == True:
                    return

                # 23
                bb3.on()
                a4.on()
                sleep(.3)
                a4.off()
                d4.on()
                sleep(.3)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                g4.on()
                sleep(.15)
                bb3.off()
                g4.off()
                f3.on()
                a4.on()
                sleep(.45)
                a4.off()
                sleep(.45)
                f3.off()
                if stop == True:
                    return

                # 24

                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                if stop == True:
                    return
                # 25
                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                if stop == True:
                    return

                # 26
                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                if stop == True:
                    return

                # 27
                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                i += 1

                if stop == True:
                    return


            i = 0
            while i < 2:
                # 28 & 30
                if stop == True:
                    return

                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.3)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e3.off()
                if stop == True:
                    return
                # 29 & 31

                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.3)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e3.off()
                i += 1

                if stop == True:
                    return


            d3.on()  # ending chord
            d4.on()
            f4.on()
            a4.on()
            sleep(.9)
            d3.off()
            d4.off()
            f4.off()
            a4.off()

            return


    thread = threading.Thread(target=run)
    thread.start()

def FunctionB(): #WII THEME SONG
    def run1():
        while stop == False:
            # 1 INTRO
            if stop == True:
                return

            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.2)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.2)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()

            b4.off()
            d5.off()
            sleep(.1)
            if stop == True:
                return

            # 2
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.2)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.2)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.05)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.05)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.05)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.05)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.05)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.05)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.05)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.05)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.2)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.2)
            if stop == True:
                break

            # 3
            sleep(1.6)
            # 4
            sleep(1.6)

            i = 0
            while i < 2:

                if stop == True:
                    return

                # 5
                sleep(.2)
                a4.on()
                d4.on()
                b3.on()
                sleep(.1)
                a4.off()
                d4.off()
                b3.off()
                sleep(.1)
                a4.on()
                d4.on()
                b3.on()
                sleep(.2)
                a4.off()
                d4.off()
                b3.off()
                sleep(.2)
                g4.on()
                d4.on()
                b3.on()
                sleep(.1)
                g4.off()
                d4.off()
                b3.off()
                sleep(.1)
                g4.on()
                d4.on()
                b3.on()
                sleep(.1)
                g4.off()
                d4.off()
                b3.off()
                sleep(.1)
                sleep(.2)
                fs4.on()
                d4.on()
                b3.on()
                sleep(.1)
                fs4.off()
                d4.off()
                b3.off()
                sleep(.1)
                if stop == True:
                    return

                # 6
                fs4.on()
                d4.on()
                b3.on()
                sleep(.2)
                fs4.off()
                d4.off()
                b3.off()
                sleep(.2)
                e4.on()
                d4.on()
                b3.on()
                sleep(.1)
                e4.off()
                d4.off()
                b3.off()
                sleep(.1)
                e4.on()
                d4.on()
                b3.on()
                sleep(.1)
                e4.off()
                d4.off()
                b3.off()
                sleep(.1)
                sleep(.8)
                if stop == True:
                    return

                # 7
                sleep(.2)
                a4.on()
                d4.on()
                b3.on()
                sleep(.1)
                a4.off()
                d4.off()
                b3.off()
                sleep(.1)
                a4.on()
                d4.on()
                b3.on()
                sleep(.2)
                a4.off()
                d4.off()
                b3.off()
                sleep(.2)
                g4.on()
                d4.on()
                b3.on()
                sleep(.1)
                g4.off()
                d4.off()
                b3.off()
                sleep(.1)
                g4.on()
                d4.on()
                b3.on()
                sleep(.1)
                g4.off()
                d4.off()
                b3.off()
                sleep(.1)
                sleep(.2)
                fs4.on()
                d4.on()
                b3.on()
                sleep(.1)
                fs4.off()
                d4.off()
                b3.off()
                sleep(.1)
                if stop == True:
                    return

                # 8
                fs4.on()
                d4.on()
                b3.on()
                sleep(.2)
                fs4.off()
                d4.off()
                b3.off()
                sleep(.2)
                e4.on()
                d4.on()
                b3.on()
                sleep(.1)
                e4.off()
                d4.off()
                b3.off()
                sleep(.1)
                e4.on()
                d4.on()
                b3.on()
                sleep(.1)
                e4.off()
                d4.off()
                b3.off()
                sleep(.1)
                sleep(.8)
                if stop == True:
                    return

                # 9
                sleep(.2)
                e4.on()
                g4.on()
                d5.on()
                sleep(.1)
                e4.off()
                g4.off()
                d5.off()
                sleep(.1)
                e4.on()
                g4.on()
                d5.on()
                sleep(.2)
                e4.off()
                g4.off()
                d5.off()
                sleep(.2)
                e4.on()
                g4.on()
                c5.on()
                sleep(.1)
                e4.off()
                g4.off()
                c5.off()
                sleep(.1)
                e4.on()
                g4.on()
                c5.on()
                sleep(.1)
                e4.off()
                g4.off()
                c5.off()
                sleep(.1)
                sleep(.2)
                e4.on()
                g4.on()
                b4.on()
                sleep(.1)
                e4.off()
                g4.off()
                b4.off()
                sleep(.1)

                if stop == True:
                    return

                # 10
                e4.on()
                g4.on()
                b4.on()
                sleep(.2)
                e4.off()
                g4.off()
                b4.off()
                sleep(.2)
                e4.on()
                g4.on()
                a4.on()
                sleep(.1)
                e4.off()
                g4.off()
                a4.off()
                sleep(.1)
                e4.on()
                g4.on()
                a4.on()
                sleep(.1)
                e4.off()
                g4.off()
                a4.off()
                sleep(.1)
                sleep(.8)
                if stop == True:
                    return

                # 11
                sleep(.2)
                eb4.on()
                g4.on()
                d5.on()
                sleep(.1)
                eb4.off()
                g4.off()
                d5.off()
                sleep(.1)
                eb4.on()
                g4.on()
                d5.on()
                sleep(.2)
                eb4.off()
                g4.off()
                d5.off()
                sleep(.2)
                eb4.on()
                g4.on()
                c5.on()
                sleep(.1)
                eb4.off()
                g4.off()
                c5.off()
                sleep(.1)
                eb4.on()
                g4.on()
                c5.on()
                sleep(.1)
                eb4.off()
                g4.off()
                c5.off()
                sleep(.1)
                sleep(.2)
                c4.on()
                eb4.on()
                bb4.on()
                sleep(.1)
                c4.off()
                eb4.off()
                bb4.off()
                sleep(.1)
                if stop == True:
                    return

                # 12
                c4.on()
                eb4.on()
                bb4.on()
                sleep(.2)
                c4.off()
                eb4.off()
                bb4.off()
                sleep(.2)
                c4.on()
                eb4.on()
                a4.on()
                sleep(.1)
                c4.off()
                eb4.off()
                a4.off()
                sleep(.1)
                c4.on()
                eb4.on()
                a4.on()
                sleep(.1)
                c4.off()
                eb4.off()
                a4.off()
                sleep(.1)
                sleep(.2)
                eb4.on()
                g4.on()
                sleep(.6)
                eb4.off()
                g4.off()
                if stop == True:
                    return

                # 13
                fs4.on()
                d4.on()
                sleep(.4)
                fs4.off()
                d4.off()
                sleep(.4)
                fs4.on()
                d4.on()
                sleep(.4)
                fs4.off()
                d4.off()
                a4.on()
                sleep(.2)
                a4.off()
                e4.on()
                cs4.on()
                sleep(.2)
                if stop == True:
                    return

                # 14
                sleep(1.6)
                e4.off()
                cs4.off()
                if stop == True:
                    return

                # 15
                sleep(.6)
                d4.on()
                sleep(.2)
                d4.off()
                e4.on()
                sleep(.2)
                e4.off()
                fs4.on()
                sleep(.2)
                fs4.off()
                c4.on()
                g4.on()
                sleep(.1)
                c4.off()
                g4.off()
                sleep(.1)
                c4.on()
                a4.on()
                sleep(.2)
                c4.off()
                a4.off()
                if stop== True:
                    return

                # 16
                b4.on()
                ab4.on()
                f4.on()
                sleep(.4)
                b4.off()
                ab4.off()
                f4.off()
                sleep(.4)
                c5.on()
                ab4.on()
                f4.on()
                sleep(.4)
                c5.off()
                ab4.off()
                f4.off()
                sleep(.4)
                if stop == True:
                    return

                # 17
                b4.on()
                g4.on()
                sleep(.4)
                b4.off()
                g4.off()
                e4.on()
                c4.on()
                sleep(.1)
                e4.off()
                c4.off()
                sleep(.1)
                e4.on()
                c4.on()
                sleep(.2)
                e4.off()
                c4.off()
                sleep(.2)
                g4.on()
                b4.on()
                sleep(.2)
                g4.off()
                b4.off()
                sleep(.2)
                fs4.on()
                bb4.on()
                sleep(.2)
                if stop == True:
                    return

                # 18
                sleep(.4)
                fs4.off()
                bb4.off()
                eb4.on()
                c4.on()
                sleep(.1)
                eb4.off()
                c4.off()
                sleep(.1)
                eb4.on()
                c4.on()
                sleep(.2)
                eb4.off()
                c4.off()
                sleep(.2)
                bb4.on()
                fs4.on()
                sleep(.2)
                bb4.off()
                fs4.off()
                sleep(.2)
                b3.on()
                d4.on()
                fs4.on()
                a4.on()
                sleep(.2)
                if stop == True:
                    return

                # 19
                sleep(.8)
                b3.off()
                d4.off()
                fs4.off()
                a4.off()
                sleep(.2)
                fs4.on()
                d4.on()
                sleep(.2)
                fs4.off()
                d4.off()
                sleep(.4)
                if stop == True:
                    return

                # 20
                sleep(.4)
                a4.on()
                cs5.on()
                e5.on()
                sleep(.1)
                a4.off()
                cs5.off()
                e5.off()
                sleep(.1)
                a4.on()
                cs5.on()
                e5.on()
                sleep(.1)
                a4.off()
                cs5.off()
                e5.off()
                sleep(.1)
                a4.on()
                c5.on()
                eb5.on()
                sleep(.1)
                a4.off()
                c5.off()
                eb5.off()
                sleep(.1)
                a4.on()
                c5.on()
                eb5.on()
                sleep(.1)
                a4.off()
                c5.off()
                eb5.off()
                sleep(.1)
                a4.on()
                c5.on()
                eb5.on()
                sleep(.4)
                a4.off()
                c5.off()
                eb5.off()
                if stop == True:
                    return

                # 21
                sleep(.2)
                fs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                fs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                fs4.on()
                ab4.on()
                b4.on()
                sleep(.2)
                fs4.off()
                ab4.off()
                b4.off()
                sleep(.2)
                e5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                e5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                e5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                e5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                sleep(.2)
                eb5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                eb5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                if stop == True:
                    return

                # 22
                eb5.on()
                b4.on()
                ab4.on()
                sleep(.2)
                eb5.off()
                b4.off()
                ab4.off()
                sleep(.2)
                cs5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                cs5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                cs5.on()
                b4.on()
                ab4.on()
                sleep(.2)
                cs5.off()
                b4.off()
                ab4.off()
                sleep(.8)
                if stop == True:
                    return

                # 23
                sleep(.2)
                fs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                fs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                fs4.on()
                ab4.on()
                b4.on()
                sleep(.2)
                fs4.off()
                ab4.off()
                b4.off()
                sleep(.2)
                e5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                e5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                e5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                e5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                sleep(.2)
                eb5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                eb5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                if stop == True:
                    return

                # 24
                eb5.on()
                b4.on()
                ab4.on()
                sleep(.2)
                eb5.off()
                b4.off()
                ab4.off()
                sleep(.2)
                cs5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                cs5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                cs5.on()
                b4.on()
                ab4.on()
                sleep(.2)
                cs5.off()
                b4.off()
                ab4.off()
                sleep(.8)
                if stop == True:
                    return

                # 25
                sleep(.2)
                fs4.on()
                g4.on()
                b4.on()
                sleep(.1)
                fs4.off()
                g4.off()
                b4.off()
                sleep(.1)
                fs4.on()
                g4.on()
                b4.on()
                sleep(.2)
                fs4.off()
                g4.off()
                b4.off()
                sleep(.2)
                e5.on()
                b4.on()
                g4.on()
                sleep(.1)
                e5.off()
                b4.off()
                g4.off()
                sleep(.1)
                e5.on()
                b4.on()
                g4.on()
                sleep(.1)
                e5.off()
                b4.off()
                g4.off()
                sleep(.1)
                sleep(.2)
                d5.on()
                b4.on()
                g4.on()
                sleep(.1)
                d5.off()
                b4.off()
                g4.off()
                sleep(.1)
                if stop == True:
                    return

                # 26
                d5.on()
                b4.on()
                g4.on()
                sleep(.2)
                d5.off()
                b4.off()
                g4.off()
                sleep(.2)
                cs5.on()
                b4.on()
                g4.on()
                sleep(.1)
                cs5.off()
                b4.off()
                g4.off()
                sleep(.1)
                cs5.on()
                b4.on()
                g4.on()
                sleep(.2)
                cs5.off()
                b4.off()
                g4.off()
                sleep(.8)
                if stop == True:
                    return

                # 27
                sleep(.2)
                fs4.on()
                a4.on()
                e5.on()
                sleep(.1)
                fs4.off()
                a4.off()
                e5.off()
                sleep(.1)
                fs4.on()
                a4.on()
                e5.on()
                sleep(.2)
                fs4.off()
                a4.off()
                e5.off()
                sleep(.2)
                d5.on()
                a4.on()
                fs4.on()
                sleep(.1)
                d5.off()
                a4.off()
                fs4.off()
                sleep(.1)
                d5.on()
                a4.on()
                fs4.on()
                sleep(.1)
                d5.off()
                a4.off()
                fs4.off()
                sleep(.1)
                sleep(.2)
                cs5.on()
                a4.on()
                fs4.on()
                sleep(.1)
                cs5.off()
                a4.off()
                fs4.off()
                sleep(.1)
                if stop == True:
                    return

                # 28
                cs5.on()
                a4.on()
                fs4.on()
                sleep(.2)
                cs5.off()
                a4.off()
                fs4.off()
                sleep(.2)
                fs4.on()
                b4.on()
                a4.on()
                sleep(.1)
                fs4.off()
                b4.off()
                a4.off()
                sleep(.1)
                fs4.on()
                b4.on()
                a4.on()
                sleep(.2)
                fs4.off()
                b4.off()
                a4.off()
                sleep(.2)
                cs4.on()
                f4.on()
                a4.on()
                sleep(.6)
                cs4.off()
                f4.off()
                a4.off()
                if stop == True:
                    return

                # 29
                b3.on()
                e4.on()
                ab4.on()
                sleep(.2)
                b3.off()
                e4.off()
                ab4.off()
                sleep(.2)
                ab4.on()
                e4.on()
                sleep(.1)
                ab4.off()
                e4.off()
                sleep(.1)
                ab4.on()
                e4.on()
                sleep(.1)
                ab4.off()
                e4.off()
                sleep(.1)
                sleep(.2)
                ab4.on()
                b4.on()
                sleep(.2)
                ab4.off()
                b4.off()
                sleep(.2)
                eb4.on()
                fs4.on()
                sleep(.2)
                if stop == True:
                    return

                # 30
                sleep(1.6)
                # 31
                if stop == True:
                    return

                eb4.off()
                fs4.off()
                sleep(.2)
                fs4.on()
                d4.on()
                sleep(.2)
                fs4.off()
                d4.off()
                sleep(.2)
                f4.on()
                cs4.on()
                sleep(.2)
                f4.off()
                cs4.off()
                fs4.on()
                d4.on()
                sleep(.2)
                fs4.off()
                d4.off()
                e4.on()
                ab4.on()
                sleep(.2)
                e4.off()
                ab4.off()
                fs4.on()
                a4.on()
                sleep(.2)
                fs4.off()
                a4.off()
                ab4.on()
                b4.on()
                sleep(.1)
                ab4.off()
                b4.off()
                sleep(.1)
                if stop == True:
                    return

                # 32
                cs5.on()
                ab4.on()
                d4.on()
                sleep(.4)
                cs5.off()
                ab4.off()
                d4.off()
                sleep(.4)
                c5.on()
                ab4.on()
                d4.on()
                sleep(.4)
                c5.off()
                ab4.off()
                d4.off()
                sleep(.4)
                if stop == True:
                    return

                # 33
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.4)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.4)
                if stop == True:
                    return

                # 34
                sleep(.4)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.2)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.2)
                if stop == True:
                    return

                # 35
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.4)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.4)
                if stop == True:
                    return

                # 36
                sleep(.8)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.05)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.05)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.05)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.05)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.05)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.05)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.05)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.05)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.2)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.2)
                i += 1
                if stop == True:
                    return

            # 37 ENDING
            sleep(.2)
            b3.on()
            d4.on()
            a4.on()
            sleep(.1)
            b3.off()
            d4.off()
            a4.off()
            sleep(.1)
            b3.on()
            d4.on()
            a4.on()
            sleep(.2)
            b3.off()
            d4.off()
            a4.off()
            sleep(.2)
            b3.on()
            d4.on()
            g4.on()
            sleep(.1)
            b3.off()
            d4.off()
            g4.off()
            sleep(.1)
            b3.on()
            d4.on()
            g4.on()
            sleep(.2)
            b3.off()
            d4.off()
            g4.off()
            sleep(.2)
            fs4.on()
            d4.on()
            b3.on()
            sleep(.1)
            fs4.off()
            d4.off()
            b3.off()
            sleep(.1)
            if stop == True:
                return

            # 38
            b3.on()
            d4.on()
            fs4.on()
            sleep(.2)
            b3.off()
            d4.off()
            fs4.off()
            sleep(.2)
            b3.on()
            d4.on()
            e4.on()
            sleep(.1)
            b3.off()
            d4.off()
            e4.off()
            sleep(.1)
            b3.on()
            d4.on()
            e4.on()
            sleep(.2)
            b3.off()
            d4.off()
            e4.off()
            sleep(.2)
            b3.on()
            d4.on()
            fs4.on()
            sleep(.2)
            b3.off()
            d4.off()
            e4.off()
            sleep(.2)
            b3.on()
            d4.on()
            g4.on()
            sleep(.1)
            b3.off()
            d4.off()
            g4.off()
            sleep(.1)
            if stop == True:
                return

            # 39
            b3.on()
            d4.on()
            fs4.on()
            sleep(1.6)
            b3.off()
            d4.off()
            fs4.off()
            if stop == True:
                return
        if stop == True:
            return


    thread = threading.Thread(target=run1)
    thread.start()


def functionC(): # MII CHANNEL
    def run3():
        while stop == False:

            i = 0
            while i < 3:
                # 1
                if stop == True:
                    return

                d4.on()
                fs4.on()
                sleep(.25)
                d4.off()
                fs4.off()
                sleep(.25)
                fs4.on()
                a4.on()
                sleep(.125)
                fs4.off()
                a4.off()
                sleep(.125)
                a4.on()
                cs5.on()
                sleep(.25)
                a4.off()
                cs5.off()
                sleep(.25)
                fs4.on()
                a4.on()
                sleep(.25)
                fs4.off()
                a4.off()
                sleep(.25)
                fs4.on()
                d4.on()
                sleep(.125)
                fs4.off()
                d4.off()
                sleep(.125)
                # 2
                if stop == True:
                    return
                d4.on()
                sleep(.125)
                d4.off()
                sleep(.125)
                d4.on()
                sleep(.125)
                d4.off()
                sleep(.125)
                d4.on()
                sleep(.125)
                d4.off()
                sleep(.125)
                sleep(.25)
                sleep(.5)
                sleep(.25)
                cs4.on()
                bb3.on()
                sleep(.25)
                cs4.off()
                bb3.off()
                if stop == True:
                    return

                # 3
                b3.on()
                d4.on()
                sleep(.125)
                b3.off()
                d4.off()
                sleep(.125)
                d4.on()
                fs4.on()
                sleep(.125)
                d4.off()
                fs4.off()
                sleep(.125)
                fs4.on()
                a4.on()
                sleep(.125)
                fs4.off()
                a4.off()
                sleep(.125)
                cs5.on()
                a4.on()
                sleep(.25)
                cs5.off()
                a4.off()
                sleep(.25)
                a4.on()
                fs4.on()
                sleep(.25)
                a4.off()
                fs4.off()
                sleep(.25)
                fs4.on()
                d4.on()
                sleep(.25)
                fs4.off()
                d4.off()
                if stop == True:
                    return
                # 4
                e5.on()
                ab4.on()
                e4.on()
                ab3.on()
                sleep(.5)
                sleep(.25)
                e5.off()
                ab4.off()
                e4.off()
                ab3.off()
                eb5.on()
                g4.on()
                eb4.on()
                g3.on()
                sleep(.25)
                eb5.off()
                g4.off()
                eb4.off()
                g3.off()
                d5.on()
                fs4.on()
                d4.on()
                fs3.on()
                sleep(.25)
                d5.off()
                fs4.off()
                d4.off()
                fs3.off()
                sleep(.25)
                sleep(.5)
                if stop == True:
                    return

                # 5
                ab4.on()
                sleep(.25)
                ab4.off()
                sleep(.25)
                cs5.on()
                e4.on()
                cs4.on()
                sleep(.25)
                cs5.off()
                e4.off()
                cs4.off()
                fs4.on()
                a3.on()
                sleep(.25)
                fs4.off()
                a3.off()
                sleep(.25)
                cs5.on()
                e4.on()
                cs4.on()
                e3.on()
                sleep(.25)
                cs5.off()
                e4.off()
                cs4.off()
                e3.off()
                sleep(.25)
                ab4.on()
                a3.on()
                sleep(.25)
                ab4.off()
                a3.off()
                if stop == True:
                    return

                # 6
                sleep(.25)
                cs5.on()
                e4.on()
                cs4.on()
                sleep(.25)
                cs5.off()
                e4.off()
                cs4.off()
                sleep(.25)
                g4.on()
                g3.on()
                sleep(.25)
                g4.off()
                g3.off()
                fs4.on()
                fs3.on()
                sleep(.25)
                fs4.off()
                fs3.off()
                sleep(.25)
                e4.on()
                cs4.on()
                sleep(.25)
                e4.off()
                cs4.off()
                sleep(.25)
                if stop == True:
                    return

                # 7
                e4.on()
                c4.on()
                fs3.on()
                # d3.on()
                sleep(.125)
                e4.off()
                c4.off()
                fs3.off()
                # d3.off()
                sleep(.125)
                e4.on()
                c4.on()
                fs3.on()
                # d3.on()
                sleep(.125)
                e4.off()
                c4.off()
                fs3.off()
                # d3.off()
                sleep(.125)
                e4.on()
                c4.on()
                fs3.on()
                # d3.on()
                sleep(.125)
                e4.off()
                c4.off()
                fs3.off()
                # d3.off()
                sleep(.125)
                sleep(.25)
                sleep(.5)
                e4.on()
                c4.on()
                fs3.on()
                # d3.on()
                sleep(.125)
                e4.off()
                c4.off()
                fs3.off()
                # d3.off()
                sleep(.125)
                e4.on()
                c4.on()
                fs3.on()
                # d3.on()
                sleep(.125)
                e4.off()
                c4.off()
                fs3.off()
                # d3.off()
                sleep(.125)
                if stop == True:
                    return

                # 8
                e4.on()
                c4.on()
                fs3.on()
                # d3.on()
                sleep(.125)
                e4.off()
                c4.off()
                fs3.off()
                # d3.off()
                sleep(.125)
                sleep(.25)
                sleep(.5)
                eb4.on()
                b3.on()
                ab3.on()
                sleep(.5)
                eb4.off()
                b3.off()
                ab3.off()
                d4.on()
                bb3.on()
                g3.on()
                sleep(.5)
                d4.off()
                bb3.off()
                g3.off()
                if stop == True:
                    return

                #9
                cs4.on()
                a3.on()
                sleep(.25)
                cs4.off()
                a3.off()
                sleep(.25)
                fs4.on()
                a4.on()
                sleep(.125)
                fs4.off()
                a4.off()
                sleep(.125)
                a4.on()
                cs5.on()
                sleep(.25)
                a4.off()
                cs5.off()
                sleep(.25)
                a4.on()
                fs4.on()
                sleep(.25)
                a4.off()
                fs4.off()
                sleep(.25)
                fs4.on()
                eb4.on()
                sleep(.25)
                fs4.off()
                eb4.off()
                if stop == True:
                    return

                # 10
                e4.on()
                d4.on()
                ab3.on()
                sleep(.125)
                e4.off()
                d4.off()
                ab3.off()
                sleep(.125)
                e4.on()
                d4.on()
                ab3.on()
                sleep(.125)
                e4.off()
                d4.off()
                ab3.off()
                sleep(.125)
                e4.on()
                d4.on()
                ab3.on()
                sleep(.125)
                e4.off()
                d4.off()
                ab3.off()
                sleep(.125)
                sleep(.25)
                e5.on()
                ab4.on()
                sleep(.125)
                e5.off()
                ab4.off()
                sleep(.125)
                e5.on()
                ab4.on()
                sleep(.125)
                e5.off()
                ab4.off()
                sleep(.125)
                e5.on()
                ab4.on()
                sleep(.125)
                e5.off()
                ab4.off()
                sleep(.125)
                sleep(.25)
                if stop == True:
                    return

                # 11
                g3.on()
                sleep(.25)
                g3.off()
                fs4.on()
                d4.on()
                sleep(.125)
                fs4.off()
                d4.off()
                sleep(.125)
                fs4.on()
                a4.on()
                sleep(.125)
                fs4.off()
                a4.off()
                sleep(.125)
                cs5.on()
                a4.on()
                sleep(.25)
                cs5.off()
                a4.off()
                sleep(.25)
                fs4.on()
                a4.on()
                sleep(.25)
                fs4.off()
                a4.off()
                sleep(.25)
                fs4.on()
                d4.on()
                sleep(.25)
                fs4.off()
                d4.off()
                if stop == True:
                    return

                # 12
                cs5.on()
                ab4.on()
                e4.on()
                e3.on()
                sleep(.5)
                sleep(.5)
                cs5.off()
                ab4.off()
                e4.off()
                e3.off()
                b4.on()
                fs4.on()
                d4.on()
                d3.on()
                sleep(.25)
                b4.off()
                fs4.off()
                d4.off()
                d3.off()
                sleep(.25)
                sleep(.5)
                if stop == True:
                    return

                # 13
                b4.on()
                d3.on()
                sleep(.25)
                b4.off()
                d3.off()
                g4.on()
                sleep(.25)
                g4.off()
                d4.on()
                ab3.on()
                sleep(.25)
                d4.off()
                ab3.off()
                cs4.on()
                a3.on()
                sleep(.5)
                cs4.off()
                a3.off()
                b4.on()
                sleep(.25)
                b4.off()
                g4.on()
                e3.on()
                sleep(.25)
                g4.off()
                e3.off()
                cs4.on()
                sleep(.25)
                cs4.off()
                if stop == True:
                    return

                # 14
                a4.on()
                d3.on()
                sleep(.25)
                a4.off()
                d3.off()
                fs4.on()
                sleep(.25)
                fs4.off()
                c4.on()
                fs3.on()
                sleep(.25)
                c4.off()
                fs3.off()
                b3.on()
                g3.on()
                sleep(.5)
                b3.off()
                g3.off()
                f4.on()
                sleep(.25)
                f4.off()
                d4.on()
                g3.on()
                sleep(.25)
                d4.off()
                g3.off()
                b3.on()
                fs3.on()
                sleep(.25)
                b3.off()
                fs3.off()
                if stop == True:
                    return
                # 15
                e4.on()
                cs4.on()
                d3.on()
                sleep(.125)
                e4.off()
                cs4.off()
                d3.on()
                sleep(.125)
                e4.on()
                cs4.on()
                d3.on()
                sleep(.125)
                e4.off()
                cs4.off()
                d3.on()
                sleep(.125)
                e4.on()
                cs4.on()
                d3.on()
                sleep(.125)
                e4.off()
                cs4.off()
                d3.on()
                sleep(.125)
                sleep(.25)
                sleep(.5)
                sleep(.25)
                bb3.on()
                sleep(.25)
                bb3.off()
                if stop == True:
                    return

                # 16
                b3.on()
                sleep(.25)
                b3.off()
                cs4.on()
                sleep(.25)
                cs4.off()
                d4.on()
                sleep(.25)
                d4.off()
                fs4.on()
                d3.on()
                sleep(.25)
                fs4.off()
                d3.off()
                a4.on()
                fs3.on()
                sleep(.25)
                a4.off()
                fs3.off()
                sleep(.25)
                sleep(.5)
                if stop == True:
                    return
                # 17
                sleep(.5)
                sleep(.5)
                a3.on()
                sleep(.5)
                a3.off()
                bb3.on()
                sleep(.5)
                bb3.off()
                if stop == True:
                    return

                # 18
                b3.on()
                e3.on()
                sleep(.25)
                b3.off()
                e3.off()
                sleep(.25)
                e3.on()
                g3.on()
                sleep(.25)
                e3.off()
                g3.off()
                bb3.on()
                sleep(.25)
                bb3.off()
                b3.on()
                sleep(.25)
                b3.off()
                g3.on()
                e3.on()
                sleep(.25)
                g3.off()
                e3.off()
                sleep(.25)
                sleep(.25)
                if stop == True:
                    return

                # 19
                sleep(.25)
                e3.on()
                g3.on()
                sleep(.25)
                e3.off()
                g3.off()
                a3.on()
                sleep(.25)
                a3.off()
                bb3.on()
                sleep(.25)
                bb3.off()
                b3.on()
                e3.on()
                g3.on()
                sleep(.25)
                b3.off()
                e3.off()
                g3.off()
                fs4.on()
                sleep(.25)
                fs4.off()
                e3.on()
                g3.on()
                sleep(.25)
                e3.off()
                g3.off()
                cs4.on()
                sleep(.25)
                cs4.off()
                if stop == True:
                    return

                # 20
                b3.on()
                d3.on()
                sleep(.25)
                b3.off()
                d3.off()
                sleep(.25)
                fs3.on()
                d3.on()
                sleep(.25)
                fs3.off()
                d3.off()
                bb3.on()
                sleep(.25)
                bb3.off()
                b3.on()
                sleep(.25)
                b3.off()
                fs3.on()
                d3.on()
                sleep(.25)
                fs3.off()
                d3.off()
                sleep(.25)
                sleep(.25)
                if stop == True:
                    return
                # 21
                sleep(.25)
                d3.on()
                fs3.on()
                sleep(.25)
                d3.off()
                fs3.off()
                sleep(.25)
                sleep(.25)
                b3.on()
                d3.on()
                fs3.on()
                sleep(.25)
                sleep(.25)
                c4.on()
                sleep(.25)
                c4.off()
                sleep(.25)
                if stop == True:
                    return
                # 22
                cs4.on()
                ab3.on()
                sleep(.25)
                cs4.off()
                ab3.off()
                sleep(.25)
                b3.on()
                sleep(.25)
                b3.off()
                c4.on()
                c3.on()
                sleep(.25)
                c4.off()
                c3.off()
                cs4.on()
                sleep(.25)
                cs4.off()
                bb3.on()
                sleep(.25)
                bb3.off()
                sleep(.25)
                sleep(.25)
                if stop == True:
                    return
                # 23
                sleep(.25)
                bb3.on()
                sleep(.25)
                bb3.off()
                cs4.on()
                sleep(.25)
                cs4.off()
                c4.on()
                sleep(.25)
                cs4.on()
                c4.off()
                sleep(.25)
                cs4.off()
                ab4.on()
                sleep(.25)
                ab4.off()
                bb3.on()
                sleep(.25)
                bb3.off()
                eb4.on()
                sleep(.25)
                eb4.off()
                if stop == True:
                    return
                # 24
                cs4.on()
                fs3.on()
                sleep(.25)
                cs4.off()
                fs3.off()
                sleep(.25)
                bb3.on()
                fs3.on()
                sleep(.25)
                bb3.off()
                fs3.off()
                eb4.on()
                sleep(.25)
                eb4.off()
                b3.on()
                sleep(.25)
                b3.off()
                bb3.on()
                fs3.on()
                sleep(.25)
                bb3.off()
                fs3.off()
                sleep(.25)
                cs5.on()
                cs4.on()
                sleep(.25)
                cs5.off()
                cs4.off()
                if stop == True:
                    return

                # 25
                d5.on()
                d4.on()
                sleep(.25)
                d5.off()
                d4.off()
                a4.on()
                fs4.on()
                e3.on()
                sleep(.25)
                a4.off()
                fs4.off()
                e3.off()
                sleep(.25)
                d4.on()
                sleep(.25)
                d4.off()
                ab4.on()
                e4.on()
                cs4.on()
                b3.on()
                sleep(.125)
                ab4.off()
                e4.off()
                cs4.off()
                b3.off()
                sleep(.125)
                ab4.on()
                e4.on()
                cs4.on()
                b3.on()
                sleep(.125)
                ab4.off()
                e4.off()
                cs4.off()
                b3.off()
                sleep(.125)
                ab4.on()
                e4.on()
                cs4.on()
                b3.on()
                sleep(.125)
                ab4.off()
                e4.off()
                cs4.off()
                b3.off()
                sleep(.125)
                sleep(.25)
                i += 1
                if stop == True:
                    return

            if stop == True:
                return


    thread = threading.Thread(target=run3)
    thread.start()



def functionD(): # CHAD SONG
    def run4():
        while stop == False:
            if stop == True:
                return
            # 1
            bb3.on()
            sleep(.215)
            bb3.off()
            eb4.on()
            sleep(.1075)
            eb4.off()
            sleep(.1075)
            if stop == True:
                return

            # 2
            eb4.on()
            sleep(1.29)
            eb4.off()
            bb3.on()
            bb4.on()
            sleep(1.29)
            bb3.off()
            bb4.off()
            sleep(.43)
            eb4.on()
            sleep(.215)
            eb4.off()
            bb3.on()
            sleep(.215)
            bb3.off()
            if stop == True:
                return
            # 3
            eb4.on()
            sleep(.215)
            eb4.off()
            bb4.on()
            sleep(.1075)
            bb4.off()
            sleep(.1075)
            bb4.on()
            sleep(.215)
            sleep(2.58)
            bb4.off()
            bb3.on()
            sleep(.215)
            bb3.off()
            eb4.on()
            sleep(.1075)
            eb4.off()
            sleep(.1075)
            if stop == True:
                return

            # 4
            eb4.on()
            f4.on()
            sleep(.86)
            eb4.off()
            f4.off()
            sleep(.43)
            bb4.on()
            bb3.on()
            f4.on()
            sleep(.86)
            sleep(.43)
            bb4.off()
            bb3.off()
            f4.off()
            sleep(.43)
            eb4.on()
            sleep(.215)
            eb4.off()
            bb3.on()
            sleep(.215)
            bb3.off()
            if stop == True:
                return

            # 5
            eb4.on()
            ab4.on()
            sleep(.1075)
            eb4.off()
            ab4.off()
            sleep(.1075)
            bb3.on()
            ab4.on()
            bb4.on()
            sleep(.1075)
            bb3.off()
            ab4.off()
            bb4.off()
            sleep(.1075)
            bb3.on()
            ab4.on()
            bb4.on()
            sleep(1.72)
            bb3.off()
            ab4.off()
            bb4.off()
            sleep(.86)
            bb3.on()
            sleep(.215)
            bb3.off()
            eb4.on()
            sleep(.215)
            eb4.off()
            if stop == True:
                return

            # 6
            ab4.on()
            sleep(.86)
            ab4.off()
            fs4.on()
            sleep(.86)
            fs4.off()
            f4.on()
            sleep(.86)
            f4.off()
            eb4.on()
            sleep(.43)
            eb4.off()
            ab4.on()
            sleep(.43)
            ab4.off()
            if stop == True:
                return

            # 7
            bb4.on()
            sleep(.215)
            bb4.off()
            eb4.on()
            sleep(.1075)
            eb4.off()
            sleep(.1075)
            eb4.on()
            sleep(.43)
            eb4.off()
            sleep(.43)
            eb4.on()
            sleep(.215)
            eb4.off()
            bb3.on()
            sleep(.215)
            bb3.off()
            eb4.on()
            sleep(.215)
            eb4.off()
            bb4.on()
            sleep(.1075)
            bb4.off()
            sleep(.1075)
            bb4.on()
            sleep(.43)
            bb4.off()
            eb4.on()
            sleep(.215)
            eb4.off()
            sleep(.215)
            eb4.on()
            sleep(.215)
            eb4.off()
            sleep(.215)
            if stop == True:
                return

            # 8
            eb4.on()
            sleep(.86)
            eb4.off()
            sleep(.86)
            sleep(.86)
            ######## sleep(.5) sleep(.325) sleep(.175) sleep(.167)
            d4.on()
            sleep(.167)
            d4.off()
            cs4.on()
            sleep(.167)
            cs4.off()
            c4.on()
            sleep(.167)
            c4.off()
            if stop == True:
                return

            # 9
            b3.on()
            sleep(.325)
            b3.off()
            g3.on()
            sleep(.175)
            g3.off()
            d3.on()
            sleep(.325)
            d3.off()
            g3.on()
            sleep(.175)
            g3.off()
            b3.on()
            sleep(.325)
            b3.off()
            g3.on()
            sleep(.175)
            g3.off()
            d4.on()
            sleep(.325)
            d4.off()
            b3.on()
            sleep(.175)
            b3.off()
            if stop == True:
                return

            # 10
            g4.on()
            sleep(.167)
            g4.off()
            fs4.on()
            sleep(.167)
            fs4.off()
            g4.on()
            sleep(.167)
            g4.off()
            a4.on()
            sleep(.167)
            a4.off()
            g4.on()
            sleep(.167)
            g4.off()
            fs4.on()
            sleep(.167)
            fs4.off()
            g4.on()
            sleep(.325)
            g4.off()
            d4.on()
            sleep(.175)
            d4.off()
            b3.on()
            sleep(.325)
            b3.off()
            g3.on()
            sleep(.175)
            g3.off()
            if stop == True:
                return

            # 11
            fs3.on()
            sleep(.325)
            fs3.off()
            e3.on()
            sleep(.175)
            e3.off()
            fs3.on()
            sleep(.325)
            fs3.off()
            g3.on()
            sleep(.175)
            g3.off()
            a3.on()
            sleep(.325)
            a3.off()
            b3.on()
            sleep(.175)
            b3.off()
            c4.on()
            sleep(.167)
            c4.off()
            b3.on()
            sleep(.167)
            b3.off()
            a3.on()
            sleep(.167)
            a3.off()
            if stop == True:
                return

            # 12
            d4.on()
            sleep(.325)
            d4.off()
            cs4.on()
            sleep(.175)
            cs4.off()
            d4.on()
            sleep(.325)
            d4.off()
            e4.on()
            sleep(.175)
            e4.off()
            fs4.on()
            sleep(.325)
            fs4.off()
            d4.on()
            sleep(.175)
            d4.off()
            c4.on()
            sleep(.325)
            c4.off()
            a3.on()
            sleep(.175)
            a3.off()
            if stop == True:
                return

            # 13
            b3.on()
            sleep(.325)
            b3.off()
            g3.on()
            sleep(.175)
            g3.off()
            d3.on()
            sleep(.325)
            d3.off()
            g3.on()
            sleep(.175)
            g3.off()
            b3.on()
            sleep(.325)
            b3.off()
            g3.on()
            sleep(.175)
            g3.off()
            d4.on()
            sleep(.325)
            d4.off()
            b3.on()
            sleep(.175)
            b3.off()
            if stop == True:
                return

            # 14
            g4.on()
            sleep(.167)
            g4.off()
            fs4.on()
            sleep(.167)
            fs4.off()
            g4.on()
            sleep(.167)
            g4.off()
            a4.on()
            sleep(.167)
            a4.off()
            g4.on()
            sleep(.167)
            g4.off()
            fs4.on()
            sleep(.167)
            fs4.off()
            g4.on()
            sleep(.325)
            g4.off()
            d4.on()
            sleep(.175)
            d4.off()
            b3.on()
            sleep(.325)
            b3.off()
            g3.on()
            sleep(.175)
            g3.off()
            if stop == True:
                return

            # 15
            b3.on()
            sleep(.167)
            b3.off()
            c4.on()
            sleep(.167)
            c4.off()
            d4.on()
            sleep(.167)
            d4.off()
            g4.on()
            sleep(.325)
            g4.off()
            d4.on()
            sleep(.175)
            d4.off()
            c4.on()
            sleep(.325)
            c4.off()
            a3.on()
            sleep(.175)
            a3.off()
            fs3.on()
            sleep(.325)
            fs3.off()
            g3.on()
            sleep(.175)
            g3.off()
            if stop == True:
                return

            # 16
            a3.on()
            sleep(.325)
            a3.off()
            g3.on()
            sleep(.0875)
            g3.off()
            sleep(.0875)
            g3.on()
            sleep(.325)
            g3.off()
            fs3.on()
            sleep(.175)
            fs3.off()
            g3.on()
            sleep(.5)
            g3.off()
            sleep(.5)
            ######### sleep(.333) sleep(.167) sleep(.083)
            # 17

            if stop == True:
                return
            sleep(.333)
            eb4.on()
            sleep(.083)
            eb4.off()
            sleep(.083)
            eb4.on()
            sleep(.083)
            eb4.off()
            sleep(.083)
            sleep(.333)
            eb4.on()
            sleep(.167)
            eb4.off()
            sleep(.167)
            if stop == True:
                return
            # 18
            sleep(.333)
            eb4.on()
            sleep(.167)
            eb4.off()
            sleep(.167)
            ab4.on()
            sleep(.167)
            ab4.off()
            sleep(.167)
            ab4.on()
            sleep(.167)
            ab4.off()
            sleep(.167)
            if stop == True:
                return
            # 19
            sleep(.333)
            eb4.on()
            sleep(.083)
            eb4.off()
            sleep(.083)
            eb4.on()
            sleep(.083)
            eb4.off()
            sleep(.083)
            sleep(.333)
            eb4.on()
            sleep(.167)
            eb4.off()
            sleep(.167)
            if stop == True:
                return

            # 20
            sleep(.333)
            eb4.on()
            sleep(.167)
            eb4.off()
            sleep(.167)
            ab4.on()
            sleep(.167)
            ab4.off()
            sleep(.167)
            ab4.on()
            sleep(.167)
            ab4.off()
            sleep(.167)
            if stop == True:
                return

            # 21
            g3.on()
            g4.on()
            sleep(.333)
            g3.off()
            g4.off()
            a3.on()
            a4.on()
            sleep(.333)
            a3.off()
            a4.off()
            b3.on()
            b4.on()
            sleep(.333)
            b3.off()
            b4.off()
            c4.on()
            c5.on()
            sleep(.333)
            if stop == True:
                return

            # 22
            sleep(.333)
            c4.off()
            c5.off()
            d4.on()
            d5.on()
            sleep(.333)
            d4.off()
            d5.off()
            e5.on()
            e4.on()
            sleep(.333)
            sleep(.333)
            e5.off()
            e4.off()
            if stop == True:
                return

            # 23
            ab4.on()
            sleep(.333)
            ab4.off()
            sleep(.333)
            sleep(.333)
            sleep(.333)
            if stop == True:
                return

            # 24
            sleep(.333)
            sleep(.333)
            sleep(.333)
            sleep(.333)
            # 25
            if stop == True:
                return

            a3.on()
            a4.on()
            sleep(.333)
            a3.off()
            a4.off()
            fs3.on()
            fs4.on()
            sleep(.333)
            fs3.off()
            fs4.off()
            a3.on()
            a4.on()
            sleep(.333)
            a3.off()
            a4.off()
            g3.on()
            g4.on()
            sleep(.333)
            g3.off()
            g4.off()
            if stop == True:
                return

            # 26
            sleep(.333)
            sleep(.333)
            sleep(.333)
            sleep(.167)
            ab4.on()
            sleep(.167)
            ab4.off()
            if stop == True:
                return

            # 27
            a3.on()
            a4.on()
            sleep(.333)
            a3.off()
            a4.off()
            fs4.on()
            fs3.on()
            sleep(.167)
            fs3.off()
            fs4.off()
            sleep(.167)
            fs3.on()
            fs4.on()
            sleep(.333)
            fs3.off()
            fs4.off()
            a4.on()
            a3.on()
            sleep(.167)
            a4.off()
            a3.off()
            g3.on()
            g4.on()
            sleep(.167)
            g3.off()
            g4.off()
            if stop == True:
                return

            # 28
            sleep(.333)
            sleep(.167)
            sleep(.083)
            fs4.on()
            sleep(.083)
            fs4.off()
            g4.on()
            sleep(.167)
            sleep(.083)
            g4.off()
            fs4.on()
            sleep(.083)
            fs4.off()
            g4.on()
            sleep(.167)
            sleep(.083)
            g4.off()
            fs4.on()
            sleep(.083)
            fs4.off()
            if stop == True:
                return

            # 29
            f4.on()
            g4.on()
            sleep(.333)
            f4.off()
            g4.off()
            sleep(.333)
            f4.on()
            g4.on()
            sleep(.333)
            f4.off()
            g4.off()
            if stop == True:
                return

            # 30
            sleep(.333)
            sleep(.167)
            sleep(.083)
            fs4.on()
            sleep(.083)
            fs4.off()
            g4.on()
            sleep(.167)
            sleep(.083)
            g4.off()
            fs4.on()
            sleep(.083)
            fs4.off()
            g4.on()
            sleep(.167)
            sleep(.083)
            g4.off()
            fs4.on()
            sleep(.083)
            fs4.off()
            if stop == True:
                return

            # 31
            fs4.on()
            g4.on()
            sleep(.333)
            fs4.off()
            g4.off()
            sleep(.333)
            fs4.on()
            g4.on()
            sleep(.333)
            fs4.off()
            g4.off()
            if stop == True:
                return
            # 32
            sleep(.167)
            eb4.on()
            sleep(.083)
            eb4.off()
            sleep(.083)
            eb4.on()
            sleep(.333)
            eb4.off()
            f4.on()
            sleep(.333)
            f4.off()
            fs4.on()
            sleep(.333)
            fs4.off()
            if stop == True:
                return

            # 33
            g3.on()
            g4.on()
            sleep(.333)
            sleep(.333)
            g3.off()
            g4.off()
            ab3.on()
            ab4.on()
            sleep(.333)
            sleep(.333)
            ab3.off()
            ab4.off()
            if stop == True:
                return

            # 34
            f3.on()
            f4.on()
            sleep(.333)
            sleep(.333)
            g3.on()
            g4.on()
            sleep(.333)
            sleep(.333)
            g3.off()
            g4.off()
            ######## sleep(.6) sleep(.3) sleep(.15)

            i = 0
            if stop == True:
                return

            while i < 2:
                # 35 & 37
                if stop == True:
                    return

                c4.on()
                sleep(.3)
                c4.off()
                e4.on()
                sleep(.3)
                e4.off()
                a4.on()
                sleep(.3)
                a4.off()
                c4.on()
                sleep(.6)
                c4.off()
                e4.on()
                sleep(.3)
                e4.off()
                a4.on()
                sleep(.3)
                a4.off()
                e4.on()
                sleep(.3)
                e4.off()
                if stop == True:
                    return

                # 36 & 38
                b3.on()
                sleep(.3)
                b3.off()
                e4.on()
                sleep(.3)
                e4.off()
                a4.on()
                sleep(.3)
                a4.off()
                b3.on()
                sleep(.6)
                b3.off()
                e4.on()
                sleep(.3)
                e4.off()
                g4.on()
                sleep(.3)
                g4.off()
                e4.on()
                sleep(.3)
                e4.off()
                i += 1

            i = 0
            if stop == True:
                return

            while i < 2:
                # 39 & 41
                if stop == True:
                    return

                c4.on()
                f3.on()
                sleep(.3)
                c4.off()
                f3.off()
                e4.on()
                sleep(.3)
                e4.off()
                a4.on()
                sleep(.3)
                a4.off()
                c4.on()
                sleep(.6)
                c4.off()
                e4.on()
                sleep(.3)
                e4.off()
                a4.on()
                f3.on()
                sleep(.3)
                a4.off()
                f3.off()
                e4.on()
                sleep(.3)
                e4.off()
                if stop == True:
                    return

                # 40 & 42
                b3.on()
                c3.on()
                sleep(.3)
                b3.off()
                c3.off()
                e4.on()
                sleep(.3)
                e4.off()
                a4.on()
                sleep(.3)
                a4.off()
                b3.on()
                sleep(.6)
                b3.off()
                e4.on()
                sleep(.3)
                e4.off()
                g4.on()
                c3.on()
                sleep(.3)
                g4.off()
                c3.off()
                e4.on()
                sleep(.3)
                e4.off()
                i += 1

            i = 0
            if stop == True:
                return

            while i < 2:
                # 43
                if stop == True:
                    return

                c4.on()
                e4.on()
                a4.on()
                f3.on()
                sleep(.15)
                c4.off()
                e4.off()
                a4.off()
                f3.off()
                sleep(.15)
                c4.on()
                e4.on()
                a4.on()
                sleep(.15)
                c4.off()
                e4.off()
                a4.off()
                sleep(.15)
                c4.on()
                e4.on()
                a4.on()
                sleep(.15)
                c4.off()
                e4.off()
                a4.off()
                sleep(.15)
                c4.on()
                e4.on()
                a4.on()
                sleep(.15)
                c4.off()
                e4.off()
                a4.off()
                sleep(.15)
                c4.on()
                e4.on()
                a4.on()
                sleep(.15)
                c4.off()
                e4.off()
                a4.off()
                sleep(.15)
                c4.on()
                e4.on()
                a4.on()
                sleep(.15)
                c4.off()
                e4.off()
                a4.off()
                sleep(.15)
                c4.on()
                e4.on()
                a4.on()
                f3.on()
                sleep(.15)
                c4.off()
                e4.off()
                a4.off()
                f3.off()
                sleep(.15)
                c4.on()
                e4.on()
                a4.on()
                sleep(.15)
                c4.off()
                e4.off()
                a4.off()
                sleep(.15)
                if stop == True:
                    return

                # 44
                b3.on()
                e4.on()
                a4.on()
                sleep(.15)
                b3.off()
                e4.off()
                a4.off()
                sleep(.15)
                b3.on()
                e4.on()
                a4.on()
                sleep(.15)
                b3.off()
                e4.off()
                a4.off()
                sleep(.15)
                b3.on()
                e4.on()
                a4.on()
                sleep(.15)
                b3.off()
                e4.off()
                a4.off()
                sleep(.15)
                b3.on()
                e4.on()
                g4.on()
                sleep(.15)
                b3.off()
                e4.off()
                g4.off()
                sleep(.15)
                b3.on()
                e4.on()
                g4.on()
                sleep(.15)
                b3.off()
                e4.off()
                g4.off()
                sleep(.15)
                b3.on()
                e4.on()
                g4.on()
                sleep(.15)
                b3.off()
                e4.off()
                g4.off()
                sleep(.15)
                b3.on()
                e4.on()
                g4.on()
                sleep(.15)
                b3.off()
                e4.off()
                g4.off()
                sleep(.15)
                b3.on()
                e4.on()
                g4.on()
                sleep(.15)
                b3.off()
                e4.off()
                g4.off()
                sleep(.15)
                i += 1
                if stop == True:
                    return
            if stop == True:
                return

    thread = threading.Thread(target=run4)
    thread.start()





image2=Image.open("/home/pi/Desktop/link.png")
photo2=ImageTk.PhotoImage(image2)
lab2 = Label(image=photo2)
lab2.pack()
lab2.place(x = 100, y = 200)

image3=Image.open("/home/pi/Desktop/bob.png")
photo3=ImageTk.PhotoImage(image3)
lab3 = Label(image=photo3)
lab3.pack()
lab3.place(x = 1200, y = 600)

image4=Image.open("/home/pi/Desktop/mii.png")
photo4=ImageTk.PhotoImage(image4)
lab4 = Label(image=photo4)
lab4.pack()
lab4.place(x = 1200, y = 200)

image5=Image.open("/home/pi/Desktop/mii_c.png")
photo5=ImageTk.PhotoImage(image5)
lab5 = Label(image=photo5)
lab5.pack()
lab5.place(x = 100, y = 600)

image6=Image.open("/home/pi/Desktop/mii_c.png")
photo6=ImageTk.PhotoImage(image6)
lab6 = Label(image=photo6)
lab6.pack()
lab6.place(x = 575, y = 750)

Label = Label(mainwindow)

song1Button = Button(mainwindow, text="Song Of Storms", fg='red', background='white', font=('Comic Sans', 40),command=switchon)
song1Button.pack()
song1Button.place()

song2Button = Button(mainwindow, text="Wii Theme Shop", fg='blue', font=('Comic Sans', 40), command=switchon2)
song2Button.pack()
song2Button.place()

song3Button = Button(mainwindow, text="Mii Theme Shop", fg='black', font=('Comic Sans', 40), command=switchon3)
song3Button.pack()
song3Button.place()

song4Button = Button(mainwindow, text="A Chadtronics Original", fg='green', font=('Comic Sans', 40), command=switchon4)
song4Button.pack()
song4Button.place()

stopButton = Button(mainwindow, text="END SONG", fg='green', font=('Comic Sans', 40), command=stop1)
stopButton.place(x=0, y=400)
mainwindow.mainloop()
