from tkinter import *
from PIL import Image, ImageTk
import threading
from time import sleep
from gpiozero import LED  # allows use of gpio ports


# 1st Octave
c3 = LED(0)
# cs3 = LED(19)
d3 = LED(1)
# eb3 = LED(20)
e3 = LED(2)
f3 = LED(3)
fs3 = LED(4)
g3 = LED(5)
ab3 = LED(6)
a3 = LED(7)
bb3 = LED(8)
b3 = LED(9)
# 2nd Octave
c4 = LED(10)
cs4 = LED(11)
d4 = LED(12)
eb4 = LED(13)
e4 = LED(14)
f4 = LED(15)
fs4 = LED(16)
g4 = LED(17)
ab4 = LED(18)
a4 = LED(19)
bb4 = LED(20)
b4 = LED(21)
# 3rd Octave
c5 = LED(22)
cs5 = LED(23)
d5 = LED(24)
eb5 = LED(25)
e5 = LED(26)
f5 = LED(27)


mainwindow = Tk()

mainwindow.geometry('1500x1500')
mainwindow.title("GUI")
mainwindow.configure(background='black')

song1 = True
song2 = True
song3 = True
song4 = True
stop = False
play = False
pause = False



def switchon():
    global stop
    stop = False
    print("Playing Song")
    FunctionA()


def switchon2():
    global stop
    stop = False
    print("Playing Song")
    FunctionB()


def switchon3():
    global stop
    stop = False
    print("Playing Song")
    functionC()


def switchon4():
    global stop
    stop = False
    print("Playing Song")
    functionD()


def stop1():
    global stop
    stop = True
    print("Ending Song")






def FunctionA():
    def run():
        while stop == False:

            if stop == True:
                break



            i = 0
            while i < 2:  # intro
                # 1 & 3
                if stop == True:
                    break

                d3.on()
                sleep(.9)
                d3.off()
                e3.on()
                sleep(.9)
                e3.off()
                # 2 & 4
                f3.on()
                sleep(.9)
                f3.off()
                e3.on()
                sleep(.9)
                e3.off()
                i += 1

            i = 0
            if stop == True:
                break

            while i < 2:
                if stop == True:
                    break
                # 5 & 7
                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                if stop == True:
                    break

                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.9)
                e3.off()
                # 6 & 8
                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()

                if stop == True:
                    break

                sleep(.15)
                f4.on()
                a4.on()
                c4.on()
                sleep(.15)
                f4.off()
                a4.off()
                c4.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.9)
                e3.off()
                i += 1

            i = 0
            if stop == True:
                break

            while i < 2:
                # 9 & 11
                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                if stop == True:
                    break
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.3)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e3.off()
                if stop == True:
                    break

                # 10 & 12
                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.3)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                if stop == True:
                    break

                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e3.off()
                i += 1


            i = 0
            if stop == True:
                break

            while i < 2:
                # 13 & 15
                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                if stop == True:
                    break

                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                # 14 & 16
                if stop == True:
                    break

                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                i += 1

            i = 0
            while i < 3:  # main melody
                # 17
                d3.on()
                d4.on()
                sleep(.15)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                d5.on()
                sleep(.6)
                d5.off()
                d3.off()
                e3.on()
                d4.on()
                sleep(.15)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                d5.on()
                sleep(.6)
                e3.off()
                d5.off()
                # 18
                f3.on()
                e5.on()
                sleep(.45)
                e5.off()
                f5.on()
                sleep(.15)
                f5.off()
                e5.on()
                sleep(.15)
                e5.off()
                f5.on()
                sleep(.15)
                f5.off()
                f3.off()
                e3.on()
                e5.on()
                sleep(.15)
                e5.off()
                c5.on()
                sleep(.15)
                c5.off()
                a4.on()
                sleep(.6)
                e3.off()
                a4.off()
                # 19
                bb3.on()
                a4.on()
                sleep(.3)
                a4.off()
                d4.on()
                sleep(.3)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                g4.on()
                sleep(.15)
                bb3.off()
                g4.off()
                f3.on()
                a4.on()
                sleep(.45)
                a4.off()
                sleep(.45)
                f3.off()
                # 20
                bb3.on()
                a4.on()
                sleep(.3)
                a4.off()
                d4.on()
                sleep(.3)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                g4.on()
                sleep(.15)
                bb3.off()
                g4.off()
                a3.on()
                e4.on()
                sleep(.9)
                a3.off()
                e4.off()
                # 21
                d3.on()
                d4.on()
                sleep(.15)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                d5.on()
                sleep(.6)
                d5.off()
                d3.off()
                e3.on()
                d4.on()
                sleep(.15)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                d5.on()
                sleep(.6)
                e3.off()
                d5.off()
                # 22
                f3.on()
                e5.on()
                sleep(.45)
                e5.off()
                f5.on()
                sleep(.15)
                f5.off()
                e5.on()
                sleep(.15)
                e5.off()
                f5.on()
                sleep(.15)
                f5.off()
                f3.off()
                e3.on()
                e5.on()
                sleep(.15)
                e5.off()
                c5.on()
                sleep(.15)
                c5.off()
                a4.on()
                sleep(.6)
                e3.off()
                a4.off()
                # 23
                bb3.on()
                a4.on()
                sleep(.3)
                a4.off()
                d4.on()
                sleep(.3)
                d4.off()
                f4.on()
                sleep(.15)
                f4.off()
                g4.on()
                sleep(.15)
                bb3.off()
                g4.off()
                f3.on()
                a4.on()
                sleep(.45)
                a4.off()
                sleep(.45)
                f3.off()
                # 24
                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                # 25
                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                # 26
                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                # 27
                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.15)
                e4.on()
                sleep(.15)
                e4.off()
                g4.on()
                b4.on()
                sleep(.6)
                g4.off()
                b4.off()
                e3.off()
                i += 1

            i = 0
            while i < 2:
                # 28 & 30
                d3.on()
                sleep(.3)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d4.on()
                f4.on()
                a4.on()
                sleep(.15)
                d4.off()
                f4.off()
                a4.off()
                sleep(.15)
                d3.off()
                e3.on()
                sleep(.3)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e3.off()
                # 29 & 31
                f3.on()
                sleep(.3)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f4.on()
                a4.on()
                c5.on()
                sleep(.15)
                f4.off()
                a4.off()
                c5.off()
                sleep(.15)
                f3.off()
                e3.on()
                sleep(.3)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e4.on()
                g4.on()
                b4.on()
                sleep(.15)
                e4.off()
                g4.off()
                b4.off()
                sleep(.15)
                e3.off()
                i += 1

            d3.on()  # ending chord
            d4.on()
            f4.on()
            a4.on()
            sleep(.9)
            d3.off()
            d4.off()
            f4.off()
            a4.off()


            # Offline_Tester.OF()

            if stop == True:
                break

    thread = threading.Thread(target=run)
    thread.start()

def FunctionB():
    def run1():
        while stop == False:
            # 1 INTRO
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            if stop == True:
                break

            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.2)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.2)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            if stop == True:
                break

            b4.off()
            d5.off()
            sleep(.1)
            # 2
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.1)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.1)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.2)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.2)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.05)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.05)
            e4.on()
            g4.on()
            if stop == True:
                break

            b4.on()
            d5.on()
            sleep(.05)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.05)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.05)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.05)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.05)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.05)
            e4.on()
            g4.on()
            b4.on()
            d5.on()
            sleep(.2)
            e4.off()
            g4.off()
            b4.off()
            d5.off()
            sleep(.2)
            if stop == True:
                break

            # 3
            sleep(1.6)
            # 4
            sleep(1.6)

            i = 0
            while i < 2:
                # 5
                sleep(.2)
                a4.on()
                d4.on()
                b3.on()
                sleep(.1)
                a4.off()
                d4.off()
                b3.off()
                sleep(.1)
                a4.on()
                d4.on()
                b3.on()
                sleep(.2)
                a4.off()
                d4.off()
                b3.off()
                sleep(.2)
                g4.on()
                d4.on()
                b3.on()
                sleep(.1)
                g4.off()
                d4.off()
                b3.off()
                sleep(.1)
                g4.on()
                d4.on()
                b3.on()
                sleep(.1)
                g4.off()
                d4.off()
                if stop == True:
                    break

                b3.off()
                sleep(.1)
                sleep(.2)
                fs4.on()
                d4.on()
                b3.on()
                sleep(.1)
                fs4.off()
                d4.off()
                b3.off()
                sleep(.1)
                # 6
                fs4.on()
                d4.on()
                b3.on()
                sleep(.2)
                fs4.off()
                d4.off()
                b3.off()
                sleep(.2)
                e4.on()
                d4.on()
                if stop == True:
                    break
                b3.on()
                sleep(.1)
                e4.off()
                d4.off()
                b3.off()
                sleep(.1)
                e4.on()
                d4.on()
                b3.on()
                sleep(.1)
                e4.off()
                d4.off()
                b3.off()
                sleep(.1)
                sleep(.8)
                # 7
                sleep(.2)
                a4.on()
                d4.on()
                b3.on()
                sleep(.1)
                a4.off()
                d4.off()
                b3.off()
                sleep(.1)
                a4.on()
                d4.on()
                b3.on()
                sleep(.2)
                a4.off()
                d4.off()
                b3.off()
                sleep(.2)
                g4.on()
                d4.on()
                b3.on()
                sleep(.1)
                if stop == True:
                    break

                g4.off()
                d4.off()
                b3.off()
                sleep(.1)
                g4.on()
                d4.on()
                b3.on()
                sleep(.1)
                g4.off()
                d4.off()
                b3.off()
                sleep(.1)
                sleep(.2)
                fs4.on()
                d4.on()
                b3.on()
                sleep(.1)
                fs4.off()
                d4.off()
                b3.off()
                sleep(.1)
                # 8
                fs4.on()
                d4.on()
                b3.on()
                sleep(.2)
                if stop == True:
                    break

                fs4.off()
                d4.off()
                b3.off()
                sleep(.2)
                e4.on()
                d4.on()
                b3.on()
                sleep(.1)
                e4.off()
                if stop == True:
                    break

                d4.off()
                b3.off()
                sleep(.1)
                e4.on()
                d4.on()
                b3.on()
                sleep(.1)
                e4.off()
                d4.off()
                b3.off()
                sleep(.1)
                sleep(.8)
                # 9
                sleep(.2)
                e4.on()
                g4.on()
                d5.on()
                sleep(.1)
                e4.off()
                g4.off()
                d5.off()
                sleep(.1)
                e4.on()
                g4.on()
                d5.on()
                sleep(.2)
                e4.off()
                g4.off()
                d5.off()
                sleep(.2)
                e4.on()
                g4.on()
                c5.on()
                sleep(.1)
                e4.off()
                g4.off()
                c5.off()
                sleep(.1)
                e4.on()
                g4.on()
                c5.on()
                sleep(.1)
                e4.off()
                g4.off()
                c5.off()
                sleep(.1)
                sleep(.2)
                e4.on()
                g4.on()
                b4.on()
                sleep(.1)
                e4.off()
                g4.off()
                b4.off()
                sleep(.1)
                # 10
                e4.on()
                g4.on()
                b4.on()
                sleep(.2)
                e4.off()
                g4.off()
                if stop == True:
                    break

                b4.off()
                sleep(.2)
                e4.on()
                g4.on()
                a4.on()
                sleep(.1)
                e4.off()
                g4.off()
                a4.off()
                sleep(.1)
                e4.on()
                g4.on()
                a4.on()
                sleep(.1)
                e4.off()
                g4.off()
                a4.off()
                sleep(.1)
                sleep(.8)
                # 11
                sleep(.2)
                eb4.on()
                g4.on()
                d5.on()
                sleep(.1)
                eb4.off()
                g4.off()
                d5.off()
                sleep(.1)
                eb4.on()
                if stop == True:
                    break

                g4.on()
                d5.on()
                sleep(.2)
                eb4.off()
                g4.off()
                d5.off()
                sleep(.2)
                eb4.on()
                g4.on()
                c5.on()
                sleep(.1)
                eb4.off()
                g4.off()
                c5.off()
                sleep(.1)
                eb4.on()
                g4.on()
                c5.on()
                sleep(.1)
                eb4.off()
                g4.off()
                c5.off()
                sleep(.1)
                sleep(.2)
                c4.on()
                eb4.on()
                bb4.on()
                sleep(.1)
                c4.off()
                eb4.off()
                bb4.off()
                sleep(.1)
                # 12
                c4.on()
                eb4.on()
                bb4.on()
                sleep(.2)
                c4.off()
                eb4.off()
                bb4.off()
                sleep(.2)
                c4.on()
                eb4.on()
                a4.on()
                sleep(.1)
                c4.off()
                eb4.off()
                a4.off()
                sleep(.1)
                c4.on()
                eb4.on()
                a4.on()
                sleep(.1)
                c4.off()
                eb4.off()
                a4.off()
                sleep(.1)
                sleep(.2)
                eb4.on()
                g4.on()
                sleep(.6)
                eb4.off()
                g4.off()
                # 13
                fs4.on()
                d4.on()
                sleep(.4)
                fs4.off()
                d4.off()
                sleep(.4)
                fs4.on()
                d4.on()
                sleep(.4)
                fs4.off()
                d4.off()
                a4.on()
                sleep(.2)
                a4.off()
                e4.on()
                cs4.on()
                sleep(.2)
                # 14
                sleep(1.6)
                e4.off()
                cs4.off()
                # 15
                sleep(.6)
                d4.on()
                sleep(.2)
                d4.off()
                e4.on()
                sleep(.2)
                e4.off()
                fs4.on()
                sleep(.2)
                fs4.off()
                c4.on()
                g4.on()
                sleep(.1)
                c4.off()
                g4.off()
                sleep(.1)
                c4.on()
                a4.on()
                sleep(.2)
                c4.off()
                a4.off()
                # 16
                b4.on()
                ab4.on()
                f4.on()
                sleep(.4)
                b4.off()
                ab4.off()
                f4.off()
                sleep(.4)
                c5.on()
                ab4.on()
                f4.on()
                sleep(.4)
                c5.off()
                ab4.off()
                f4.off()
                sleep(.4)
                # 17
                b4.on()
                g4.on()
                sleep(.4)
                b4.off()
                g4.off()
                e4.on()
                c4.on()
                sleep(.1)
                e4.off()
                c4.off()
                sleep(.1)
                e4.on()
                c4.on()
                sleep(.2)
                e4.off()
                c4.off()
                sleep(.2)
                g4.on()
                b4.on()
                sleep(.2)
                g4.off()
                b4.off()
                sleep(.2)
                fs4.on()
                bb4.on()
                sleep(.2)
                # 18
                sleep(.4)
                fs4.off()
                bb4.off()
                eb4.on()
                c4.on()
                sleep(.1)
                eb4.off()
                c4.off()
                sleep(.1)
                eb4.on()
                c4.on()
                sleep(.2)
                eb4.off()
                c4.off()
                sleep(.2)
                bb4.on()
                fs4.on()
                sleep(.2)
                bb4.off()
                fs4.off()
                sleep(.2)
                b3.on()
                d4.on()
                fs4.on()
                a4.on()
                sleep(.2)
                # 19
                sleep(.8)
                b3.off()
                d4.off()
                fs4.off()
                a4.off()
                sleep(.2)
                fs4.on()
                d4.on()
                sleep(.2)
                fs4.off()
                d4.off()
                sleep(.4)
                # 20
                sleep(.4)
                a4.on()
                cs5.on()
                e5.on()
                sleep(.1)
                a4.off()
                cs5.off()
                e5.off()
                sleep(.1)
                a4.on()
                cs5.on()
                e5.on()
                sleep(.1)
                a4.off()
                cs5.off()
                e5.off()
                sleep(.1)
                a4.on()
                c5.on()
                eb5.on()
                sleep(.1)
                a4.off()
                c5.off()
                eb5.off()
                sleep(.1)
                a4.on()
                c5.on()
                eb5.on()
                sleep(.1)
                a4.off()
                c5.off()
                eb5.off()
                sleep(.1)
                a4.on()
                c5.on()
                eb5.on()
                sleep(.4)
                a4.off()
                c5.off()
                eb5.off()
                # 21
                sleep(.2)
                fs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                fs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                fs4.on()
                ab4.on()
                b4.on()
                sleep(.2)
                fs4.off()
                ab4.off()
                b4.off()
                sleep(.2)
                e5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                e5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                e5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                e5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                sleep(.2)
                eb5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                eb5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                # 22
                eb5.on()
                b4.on()
                ab4.on()
                sleep(.2)
                eb5.off()
                b4.off()
                ab4.off()
                sleep(.2)
                cs5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                cs5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                cs5.on()
                b4.on()
                ab4.on()
                sleep(.2)
                cs5.off()
                b4.off()
                ab4.off()
                sleep(.8)
                # 23
                sleep(.2)
                fs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                fs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                fs4.on()
                ab4.on()
                b4.on()
                sleep(.2)
                fs4.off()
                ab4.off()
                b4.off()
                sleep(.2)
                e5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                e5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                e5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                e5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                sleep(.2)
                eb5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                eb5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                # 24
                eb5.on()
                b4.on()
                ab4.on()
                sleep(.2)
                eb5.off()
                b4.off()
                ab4.off()
                sleep(.2)
                cs5.on()
                b4.on()
                ab4.on()
                sleep(.1)
                cs5.off()
                b4.off()
                ab4.off()
                sleep(.1)
                cs5.on()
                b4.on()
                ab4.on()
                sleep(.2)
                cs5.off()
                b4.off()
                ab4.off()
                sleep(.8)
                # 25
                sleep(.2)
                fs4.on()
                g4.on()
                b4.on()
                sleep(.1)
                fs4.off()
                g4.off()
                b4.off()
                sleep(.1)
                fs4.on()
                g4.on()
                b4.on()
                sleep(.2)
                fs4.off()
                g4.off()
                b4.off()
                sleep(.2)
                e5.on()
                b4.on()
                g4.on()
                sleep(.1)
                e5.off()
                b4.off()
                g4.off()
                sleep(.1)
                e5.on()
                b4.on()
                g4.on()
                sleep(.1)
                e5.off()
                b4.off()
                g4.off()
                sleep(.1)
                sleep(.2)
                d5.on()
                b4.on()
                g4.on()
                sleep(.1)
                d5.off()
                b4.off()
                g4.off()
                sleep(.1)
                # 26
                d5.on()
                b4.on()
                g4.on()
                sleep(.2)
                d5.off()
                b4.off()
                g4.off()
                sleep(.2)
                cs5.on()
                b4.on()
                g4.on()
                sleep(.1)
                cs5.off()
                b4.off()
                g4.off()
                sleep(.1)
                cs5.on()
                b4.on()
                g4.on()
                sleep(.2)
                cs5.off()
                b4.off()
                g4.off()
                sleep(.8)
                # 27
                sleep(.2)
                fs4.on()
                a4.on()
                e5.on()
                sleep(.1)
                fs4.off()
                a4.off()
                e5.off()
                sleep(.1)
                fs4.on()
                a4.on()
                e5.on()
                sleep(.2)
                fs4.off()
                a4.off()
                e5.off()
                sleep(.2)
                d5.on()
                a4.on()
                fs4.on()
                sleep(.1)
                d5.off()
                a4.off()
                fs4.off()
                sleep(.1)
                d5.on()
                a4.on()
                fs4.on()
                sleep(.1)
                d5.off()
                a4.off()
                fs4.off()
                sleep(.1)
                sleep(.2)
                cs5.on()
                a4.on()
                fs4.on()
                sleep(.1)
                cs5.off()
                a4.off()
                fs4.off()
                sleep(.1)
                # 28
                cs5.on()
                a4.on()
                fs4.on()
                sleep(.2)
                cs5.off()
                a4.off()
                fs4.off()
                sleep(.2)
                fs4.on()
                b4.on()
                a4.on()
                sleep(.1)
                fs4.off()
                b4.off()
                a4.off()
                sleep(.1)
                fs4.on()
                b4.on()
                a4.on()
                sleep(.2)
                fs4.off()
                b4.off()
                a4.off()
                sleep(.2)
                cs4.on()
                f4.on()
                a4.on()
                sleep(.6)
                cs4.off()
                f4.off()
                a4.off()
                # 29
                b3.on()
                e4.on()
                ab4.on()
                sleep(.2)
                b3.off()
                e4.off()
                ab4.off()
                sleep(.2)
                ab4.on()
                e4.on()
                sleep(.1)
                ab4.off()
                e4.off()
                sleep(.1)
                ab4.on()
                e4.on()
                sleep(.1)
                ab4.off()
                e4.off()
                sleep(.1)
                sleep(.2)
                ab4.on()
                b4.on()
                sleep(.2)
                ab4.off()
                b4.off()
                sleep(.2)
                eb4.on()
                fs4.on()
                sleep(.2)
                # 30
                sleep(1.6)
                # 31
                eb4.off()
                fs4.off()
                sleep(.2)
                fs4.on()
                d4.on()
                sleep(.2)
                fs4.off()
                d4.off()
                sleep(.2)
                f4.on()
                cs4.on()
                sleep(.2)
                f4.off()
                cs4.off()
                fs4.on()
                d4.on()
                sleep(.2)
                fs4.off()
                d4.off()
                e4.on()
                ab4.on()
                sleep(.2)
                e4.off()
                ab4.off()
                fs4.on()
                a4.on()
                sleep(.2)
                fs4.off()
                a4.off()
                ab4.on()
                b4.on()
                sleep(.1)
                ab4.off()
                b4.off()
                sleep(.1)
                # 32
                cs5.on()
                ab4.on()
                d4.on()
                sleep(.4)
                cs5.off()
                ab4.off()
                d4.off()
                sleep(.4)
                c5.on()
                ab4.on()
                d4.on()
                sleep(.4)
                c5.off()
                ab4.off()
                d4.off()
                sleep(.4)
                # 33
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.4)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.4)
                # 34
                sleep(.4)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.2)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.2)
                # 35
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.1)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.1)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.4)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.4)
                # 36
                sleep(.8)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.05)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.05)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.05)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.05)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.05)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.05)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.05)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.05)
                cs4.on()
                ab4.on()
                b4.on()
                sleep(.2)
                cs4.off()
                ab4.off()
                b4.off()
                sleep(.2)
                i += 1
            # 37 ENDING
            sleep(.2)
            b3.on()
            d4.on()
            a4.on()
            sleep(.1)
            b3.off()
            d4.off()
            a4.off()
            sleep(.1)
            b3.on()
            d4.on()
            a4.on()
            sleep(.2)
            b3.off()
            d4.off()
            a4.off()
            sleep(.2)
            b3.on()
            d4.on()
            g4.on()
            sleep(.1)
            b3.off()
            d4.off()
            g4.off()
            sleep(.1)
            b3.on()
            d4.on()
            g4.on()
            sleep(.2)
            b3.off()
            d4.off()
            g4.off()
            sleep(.2)
            fs4.on()
            d4.on()
            b3.on()
            sleep(.1)
            fs4.off()
            d4.off()
            b3.off()
            sleep(.1)
            # 38
            b3.on()
            d4.on()
            fs4.on()
            sleep(.2)
            b3.off()
            d4.off()
            fs4.off()
            sleep(.2)
            b3.on()
            d4.on()
            e4.on()
            sleep(.1)
            b3.off()
            d4.off()
            e4.off()
            sleep(.1)
            b3.on()
            d4.on()
            e4.on()
            sleep(.2)
            b3.off()
            d4.off()
            e4.off()
            sleep(.2)
            b3.on()
            d4.on()
            fs4.on()
            sleep(.2)
            b3.off()
            d4.off()
            e4.off()
            sleep(.2)
            b3.on()
            d4.on()
            g4.on()
            sleep(.1)
            b3.off()
            d4.off()
            g4.off()
            sleep(.1)
            # 39
            b3.on()
            d4.on()
            fs4.on()
            sleep(1.6)
            b3.off()
            d4.off()
            fs4.off()



            if stop == True:
                break

    thread = threading.Thread(target=run1)
    thread.start()


def functionC():
    def run3():
        try:
            while stop== False:
                i = 0
                j = 0


                while i < 5:

                    print("Playing", i, " song")
                    sleep(1)


                    if stop == True:
                        break

                    print("Playing", i, " song")
                    sleep(1)
                    print("Playing", i, "song")
                    sleep(1)

                    i += 1

                    if j == 1:
                        return


                    if stop == True:
                        break


        except stop == True:

            return

    thread = threading.Thread(target=run3)
    thread.start()



def functionD():
    def run4():
        while stop == False:

            print("Song 3 playing")
            sleep(.5)

            if stop == True:
                break

    thread = threading.Thread(target=run4)
    thread.start()


Label = Label(mainwindow)

song1Button = Button(mainwindow, text="Song Of Storms", fg='red', background='white', font=('Comic Sans', 40),command=switchon)
song1Button.pack()
song1Button.place()

song2Button = Button(mainwindow, text="Wii Theme Shop", fg='blue', font=('Comic Sans', 40), command=switchon2)
song2Button.pack()
song2Button.place()

song3Button = Button(mainwindow, text="Mii Theme Shop", fg='black', font=('Comic Sans', 40), command=switchon3)
song3Button.pack()
song3Button.place()

song4Button = Button(mainwindow, text="A Chadtronics Original", fg='green', font=('Comic Sans', 40), command=switchon4)
song4Button.pack()
song4Button.place()

stopButton = Button(mainwindow, text="END SONG", fg='green', font=('Comic Sans', 40), command=stop1)
stopButton.place(x=0, y=400)
mainwindow.mainloop()
